FROM python:3.10

ENV POSTGRES_DB=password
ENV POSTGRES_USER=passwords
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_HOST=0.0.0.0
ENV POSTGRES_PORT=5432

ENV DJANGO_SECRET_KEY=django-insecure-)m&g(n$*vtap05_q$81c24q(ue4r&mr7^4=9(0ef4sv8mr#ih4
ENV DJANGO_DEBUG=False
ENV DJANGO_ALLOWED_HOSTS=0.0.0.0:8000

ENV DJANGO_DB_NAME=$POSTGRES_DB
ENV DJANGO_DB_USER=$POSTGRES_USER
ENV DJANGO_DB_PASSWORD=$POSTGRES_PASSWORD
ENV DJANGO_DB_HOST=$POSTGRES_HOST
ENV DJANGO_DB_PORT=$POSTGRES_PORT

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /

COPY . /

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
